# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-07 14:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currentSlide', models.IntegerField()),
            ],
        ),
    ]
