# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-07 15:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presenter', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='slide',
            old_name='currentSlide',
            new_name='currentslide',
        ),
        migrations.AddField(
            model_name='slide',
            name='numberofslides',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
