# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-19 16:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presenter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slide',
            name='image_file',
            field=models.ImageField(upload_to=''),
        ),
    ]
